version: '3.6'

services:
  local-ai:
    container_name: local-ai
    image: quay.io/go-skynet/local-ai:v2.6.0-cublas-cuda12-ffmpeg # With Nvidia GPU
    # image: quay.io/go-skynet/local-ai:latest # Without Nvidia GPU
    tty: true # enable colorized logs
    restart: unless-stopped # should this be on-failure ?
    ports:
      - 8080:8080
    env_file:
      - .env
    volumes:
      - ./models:/models
      - ./images/:/tmp/generated/images/
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    command: ["/usr/bin/local-ai" ]
  jupyter:
    container_name: jupyter
    image: jupyter/minimal-notebook:latest
    ports:
      - 8888:8888
    volumes:
      - ./jupyter:/home/jovyan/work
    command: ["start-notebook.sh", "--IdentityProvider.token=''"]
    
    
